In [13]:
import os
import pandas as pd
from sklearn.linear_model import LinearRegression

# Define the path to the dataset folder
dataset_folder = 'DataSet'

# List all files in the dataset folder
files = os.listdir(dataset_folder)

# Read the data from the files (assuming they are CSV files)
dataframes = []
for file in files:
    file_path = os.path.join(dataset_folder, file)
    df = pd.read_csv(file_path)
    dataframes.append(df)

    # Assign each dataframe to a variable based on the stock ticker
    adobe_df = dataframes[0]
    # amazon_df = dataframes[1]
    # apple_df = dataframes[2]
    # google_df = dataframes[3]
    # intel_df = dataframes[4]
    # meta_df = dataframes[5]
    # microsoft_df = dataframes[6]
    # salesforce_df = dataframes[7]
    # stock_data_df = dataframes[8]
    # tesla_df = dataframes[9]

    # Combine all dataframes into a single dataframe
    #combined_df = pd.concat(dataframes, ignore_index=True)
# Display the combined dataframe
print(adobe_df)

            Date        Open        High         Low       Close       Volume  \
0     2020-01-02   74.059998   75.150002   73.797501   75.087502  135480400.0   
1     2020-01-03   74.287498   75.144997   74.125000   74.357498  146322800.0   
2     2020-01-06   73.447502   74.989998   73.187500   74.949997  118387200.0   
3     2020-01-07   74.959999   75.224998   74.370003   74.597504  108872000.0   
4     2020-01-08   74.290001   76.110001   74.290001   75.797501  132079200.0   
...          ...         ...         ...         ...         ...          ...   
1232  2024-11-22  228.059998  230.720001  228.059998  229.869995   38168300.0   
1233  2024-11-25  231.460007  233.250000  229.740005  232.869995   90152800.0   
1234  2024-11-26  233.330002  235.570007  233.330002  235.059998   45986200.0   
1235  2024-11-27  234.470001  235.690002  233.809998  234.929993   33498400.0   
1236  2024-11-29  234.809998  237.809998  233.970001  237.330002   28481400.0   

      Unnamed: 6  Unnamed: 

In [33]:
#### Regression model ####
# This is the first part of the alogrithm
# After this part we will need to create the other model
# And we will have to combine both models into a single model that will be able to predict the stock price

adobe_df = pd.read_csv('DataSet/ADBE_data.csv')
adobe_df.head()


adobe_dataset = adobe_df[["Open", "High", "Low", "Close", "Volume"]]
adobe_dataset = (adobe_dataset - adobe_dataset.mean()) / adobe_dataset.std()
input_lenght = 10 # Number of days to use for prediction

train_data = []
train_data_known_output = []

for i in range(0, adobe_dataset.shape[0] - input_lenght -1):
    train_data.append(adobe_dataset.loc[adobe_dataset.index[i:i+input_lenght]].to_numpy())
    train_data_known_output.append(adobe_dataset["Open"].loc[adobe_dataset.index[i+input_lenght+1]])

# Read all the data from the dataset (all the CSVs from the dataset folder)
# Import all the data into a epoch x features x days tensor
# Normalize the data
# Split the data into training and testing data
# Create the Model and Train it.

print(train_data_known_output[0], train_data[0])

-1.2817851029440503 [[-1.47906268 -1.49162078 -1.42936362 -1.43497127 -0.58982067]
 [-1.48768046 -1.50716873 -1.43437192 -1.46220915 -0.81970581]
 [-1.49681757 -1.49752908 -1.43958877 -1.44245651 -0.65413278]
 [-1.43597317 -1.48840757 -1.39660195 -1.44578304 -0.30520894]
 [-1.43950336 -1.44238561 -1.38522925 -1.39920846 -0.44581505]
 [-1.3737786  -1.41564327 -1.3352517  -1.3723862  -0.79256543]
 [-1.35394729 -1.39957718 -1.32033158 -1.37903989 -0.87387511]
 [-1.35924242 -1.37501116 -1.30363758 -1.31853418 -0.54573845]
 [-1.30244723 -1.35904882 -1.28350061 -1.32893034 -0.43138105]
 [-1.30857318 -1.35666469 -1.29069989 -1.34649987 -0.46543191]]
